CREATE DATABASE BKTUTOR;
USE BKTUTOR;
# DROP DATABASE BKTUTOR;
CREATE TABLE NguoiDung(
	CCCD CHAR(10) PRIMARY KEY,
    HoVaTen VARCHAR(20) NOT NULL,
    GioiTinh BOOLEAN,
    NgaySinh DATE NOT NULL,
    SDT VARCHAR(15),
    Email CHAR(30)
);

CREATE TABLE PhuHuynh(
	CCCD VARCHAR(10) PRIMARY KEY
);

CREATE TABLE GiaSu(
	CCCD CHAR(10) PRIMARY KEY,
    NoiLamViec VARCHAR(30)
);

CREATE TABLE DonTuyenGiaSu(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    CCCD CHAR(10) NOT NULL
    
);

CREATE TABLE DonDangKyLamGiaSu(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    CCCD CHAR(10) NOT NULL,
    ThoiGianTao DATETIME NOT NULL,
    TranngThaiDuyet VARCHAR(10) NOT NULL
);

CREATE TABLE CV(
	CV_ID INT AUTO_INCREMENT PRIMARY KEY,
    CCCD CHAR(10) NOT NULL,
    HinhAnh VARCHAR(40),
    TrinhDoHocVan VARCHAR(30)
);

CREATE TABLE CV_BangCap(
	CV_ID INT AUTO_INCREMENT NOT NULL,
    BangCap VARCHAR(30) NOT NULL,
    CONSTRAINT PK_CV_BangCap PRIMARY KEY (CV_ID, BANGCAP)
);

CREATE TABLE CV_KinhNghiem(
	CV_ID INT AUTO_INCREMENT NOT NULL,
    KinhNghiem VARCHAR(30) NOT NULL,
    CONSTRAINT PK_CV_KinhNghiem PRIMARY KEY (CV_ID, KinhNghiem)
);

CREATE TABLE LopHoc(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_MonHoc INT NOT NULL,
    HocPhi DECIMAL(10,2),
    ThoiGian DATETIME,
    DiaDiem VARCHAR(20)
);

CREATE TABLE MonHoc(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    Ten VARCHAR(20) NOT NULL,
    HinhAnh VARCHAR(20)
);

CREATE TABLE TaiKhoan(
	TenDangNhap VARCHAR(20) PRIMARY KEY
);

CREATE TABLE TaiKhoanAdmin(
	TenDangNhap VARCHAR(20) PRIMARY KEY,
    MatKhau VARCHAR(20) NOT NULL
);

CREATE TABLE TaiKhoanNguoiDung(
	TenDangNhap VARCHAR(20) PRIMARY KEY,
    MatKhau VARCHAR(20) NOT NULL,
    NgayTao DATETIME,
    SoTien DECIMAL(10,2)
);

CREATE TABLE TaiKhoanPhuHuynh(
	TenDangNhap VARCHAR(20) PRIMARY KEY,
    CCCD CHAR(10) NOT NULL
);

CREATE TABLE TaiKhoanGiaSu(
	TenDangNhap VARCHAR(20) PRIMARY KEY,
    CCCD CHAR(10) NOT NULL,
    TrangThaiCapPhep VARCHAR(10) NOT NULL,
    DiemDanhGia FLOAT
);

CREATE TABLE DanhGia(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    TenDangNhap VARCHAR(20) NOT NULL,
    NguoiDanhGia VARCHAR(20),
    NoiDung VARCHAR(40)
);

CREATE TABLE TinNhan(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ThoiGian DATETIME,
    NoiDung VARCHAR(40),
    NguoiGui VARCHAR(20),
    NguoiNhan VARCHAR(20)
);

CREATE TABLE GiaSu_CO_LopHoc(
	ID_Lophoc INT AUTO_INCREMENT PRIMARY KEY,
    CCCD CHAR(10) NOT NULL
);